//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:2.0.50727.8762
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsertElectronicExemplarBJ.LIBFL_API {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReaderInfo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ReaderInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FamilyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FatherNameField;
        
        private System.DateTime DateBirthField;
        
        private bool IsRemoteReaderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BarCodeField;
        
        private System.DateTime DateRegistrationField;
        
        private System.DateTime DateReRegistrationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileTelephoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        private int WorkDepartmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HashedPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SaltField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberReaderField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FamilyName {
            get {
                return this.FamilyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FamilyNameField, value) != true)) {
                    this.FamilyNameField = value;
                    this.RaisePropertyChanged("FamilyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string FatherName {
            get {
                return this.FatherNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FatherNameField, value) != true)) {
                    this.FatherNameField = value;
                    this.RaisePropertyChanged("FatherName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime DateBirth {
            get {
                return this.DateBirthField;
            }
            set {
                if ((this.DateBirthField.Equals(value) != true)) {
                    this.DateBirthField = value;
                    this.RaisePropertyChanged("DateBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public bool IsRemoteReader {
            get {
                return this.IsRemoteReaderField;
            }
            set {
                if ((this.IsRemoteReaderField.Equals(value) != true)) {
                    this.IsRemoteReaderField = value;
                    this.RaisePropertyChanged("IsRemoteReader");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string BarCode {
            get {
                return this.BarCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BarCodeField, value) != true)) {
                    this.BarCodeField = value;
                    this.RaisePropertyChanged("BarCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime DateRegistration {
            get {
                return this.DateRegistrationField;
            }
            set {
                if ((this.DateRegistrationField.Equals(value) != true)) {
                    this.DateRegistrationField = value;
                    this.RaisePropertyChanged("DateRegistration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.DateTime DateReRegistration {
            get {
                return this.DateReRegistrationField;
            }
            set {
                if ((this.DateReRegistrationField.Equals(value) != true)) {
                    this.DateReRegistrationField = value;
                    this.RaisePropertyChanged("DateReRegistration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string MobileTelephone {
            get {
                return this.MobileTelephoneField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileTelephoneField, value) != true)) {
                    this.MobileTelephoneField = value;
                    this.RaisePropertyChanged("MobileTelephone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int WorkDepartment {
            get {
                return this.WorkDepartmentField;
            }
            set {
                if ((this.WorkDepartmentField.Equals(value) != true)) {
                    this.WorkDepartmentField = value;
                    this.RaisePropertyChanged("WorkDepartment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string HashedPassword {
            get {
                return this.HashedPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.HashedPasswordField, value) != true)) {
                    this.HashedPasswordField = value;
                    this.RaisePropertyChanged("HashedPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string Salt {
            get {
                return this.SaltField;
            }
            set {
                if ((object.ReferenceEquals(this.SaltField, value) != true)) {
                    this.SaltField = value;
                    this.RaisePropertyChanged("Salt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string NumberReader {
            get {
                return this.NumberReaderField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberReaderField, value) != true)) {
                    this.NumberReaderField = value;
                    this.RaisePropertyChanged("NumberReader");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://tempuri.org/", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LIBFL_API.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Контракт генерации сообщений с именем NumberReader из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetReaderInfo", ReplyAction="*")]
        InsertElectronicExemplarBJ.LIBFL_API.GetReaderInfoResponse GetReaderInfo(InsertElectronicExemplarBJ.LIBFL_API.GetReaderInfoRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем login из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Authorize", ReplyAction="*")]
        InsertElectronicExemplarBJ.LIBFL_API.AuthorizeResponse Authorize(InsertElectronicExemplarBJ.LIBFL_API.AuthorizeRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем strPassword из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HashPass", ReplyAction="*")]
        InsertElectronicExemplarBJ.LIBFL_API.HashPassResponse HashPass(InsertElectronicExemplarBJ.LIBFL_API.HashPassRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем login из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLoginType", ReplyAction="*")]
        InsertElectronicExemplarBJ.LIBFL_API.GetLoginTypeResponse GetLoginType(InsertElectronicExemplarBJ.LIBFL_API.GetLoginTypeRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем login из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUser", ReplyAction="*")]
        InsertElectronicExemplarBJ.LIBFL_API.GetUserResponse GetUser(InsertElectronicExemplarBJ.LIBFL_API.GetUserRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем IDSession из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertIntoBasket", ReplyAction="*")]
        InsertElectronicExemplarBJ.LIBFL_API.InsertIntoBasketResponse InsertIntoBasket(InsertElectronicExemplarBJ.LIBFL_API.InsertIntoBasketRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем PINs из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertArrayIntoBasket", ReplyAction="*")]
        InsertElectronicExemplarBJ.LIBFL_API.InsertArrayIntoBasketResponse InsertArrayIntoBasket(InsertElectronicExemplarBJ.LIBFL_API.InsertArrayIntoBasketRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем IDDATA из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetExemplarStatus", ReplyAction="*")]
        InsertElectronicExemplarBJ.LIBFL_API.GetExemplarStatusResponse GetExemplarStatus(InsertElectronicExemplarBJ.LIBFL_API.GetExemplarStatusRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем id из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBookStatus", ReplyAction="*")]
        InsertElectronicExemplarBJ.LIBFL_API.GetBookStatusResponse GetBookStatus(InsertElectronicExemplarBJ.LIBFL_API.GetBookStatusRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем id из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBookInfoByID", ReplyAction="*")]
        InsertElectronicExemplarBJ.LIBFL_API.GetBookInfoByIDResponse GetBookInfoByID(InsertElectronicExemplarBJ.LIBFL_API.GetBookInfoByIDRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем invNumber из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBookInfoByInvNumber", ReplyAction="*")]
        InsertElectronicExemplarBJ.LIBFL_API.GetBookInfoByInvNumberResponse GetBookInfoByInvNumber(InsertElectronicExemplarBJ.LIBFL_API.GetBookInfoByInvNumberRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем pwd из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangePWD", ReplyAction="*")]
        InsertElectronicExemplarBJ.LIBFL_API.ChangePWDResponse ChangePWD(InsertElectronicExemplarBJ.LIBFL_API.ChangePWDRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetReaderInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetReaderInfo", Namespace="http://tempuri.org/", Order=0)]
        public InsertElectronicExemplarBJ.LIBFL_API.GetReaderInfoRequestBody Body;
        
        public GetReaderInfoRequest() {
        }
        
        public GetReaderInfoRequest(InsertElectronicExemplarBJ.LIBFL_API.GetReaderInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetReaderInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NumberReader;
        
        public GetReaderInfoRequestBody() {
        }
        
        public GetReaderInfoRequestBody(string NumberReader) {
            this.NumberReader = NumberReader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetReaderInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetReaderInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public InsertElectronicExemplarBJ.LIBFL_API.GetReaderInfoResponseBody Body;
        
        public GetReaderInfoResponse() {
        }
        
        public GetReaderInfoResponse(InsertElectronicExemplarBJ.LIBFL_API.GetReaderInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetReaderInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public InsertElectronicExemplarBJ.LIBFL_API.ReaderInfo GetReaderInfoResult;
        
        public GetReaderInfoResponseBody() {
        }
        
        public GetReaderInfoResponseBody(InsertElectronicExemplarBJ.LIBFL_API.ReaderInfo GetReaderInfoResult) {
            this.GetReaderInfoResult = GetReaderInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthorizeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Authorize", Namespace="http://tempuri.org/", Order=0)]
        public InsertElectronicExemplarBJ.LIBFL_API.AuthorizeRequestBody Body;
        
        public AuthorizeRequest() {
        }
        
        public AuthorizeRequest(InsertElectronicExemplarBJ.LIBFL_API.AuthorizeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthorizeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public AuthorizeRequestBody() {
        }
        
        public AuthorizeRequestBody(string login, string password) {
            this.login = login;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthorizeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthorizeResponse", Namespace="http://tempuri.org/", Order=0)]
        public InsertElectronicExemplarBJ.LIBFL_API.AuthorizeResponseBody Body;
        
        public AuthorizeResponse() {
        }
        
        public AuthorizeResponse(InsertElectronicExemplarBJ.LIBFL_API.AuthorizeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthorizeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AuthorizeResult;
        
        public AuthorizeResponseBody() {
        }
        
        public AuthorizeResponseBody(string AuthorizeResult) {
            this.AuthorizeResult = AuthorizeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HashPassRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HashPass", Namespace="http://tempuri.org/", Order=0)]
        public InsertElectronicExemplarBJ.LIBFL_API.HashPassRequestBody Body;
        
        public HashPassRequest() {
        }
        
        public HashPassRequest(InsertElectronicExemplarBJ.LIBFL_API.HashPassRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HashPassRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strSol;
        
        public HashPassRequestBody() {
        }
        
        public HashPassRequestBody(string strPassword, string strSol) {
            this.strPassword = strPassword;
            this.strSol = strSol;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HashPassResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HashPassResponse", Namespace="http://tempuri.org/", Order=0)]
        public InsertElectronicExemplarBJ.LIBFL_API.HashPassResponseBody Body;
        
        public HashPassResponse() {
        }
        
        public HashPassResponse(InsertElectronicExemplarBJ.LIBFL_API.HashPassResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HashPassResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HashPassResult;
        
        public HashPassResponseBody() {
        }
        
        public HashPassResponseBody(string HashPassResult) {
            this.HashPassResult = HashPassResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLoginTypeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLoginType", Namespace="http://tempuri.org/", Order=0)]
        public InsertElectronicExemplarBJ.LIBFL_API.GetLoginTypeRequestBody Body;
        
        public GetLoginTypeRequest() {
        }
        
        public GetLoginTypeRequest(InsertElectronicExemplarBJ.LIBFL_API.GetLoginTypeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLoginTypeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        public GetLoginTypeRequestBody() {
        }
        
        public GetLoginTypeRequestBody(string login) {
            this.login = login;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLoginTypeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLoginTypeResponse", Namespace="http://tempuri.org/", Order=0)]
        public InsertElectronicExemplarBJ.LIBFL_API.GetLoginTypeResponseBody Body;
        
        public GetLoginTypeResponse() {
        }
        
        public GetLoginTypeResponse(InsertElectronicExemplarBJ.LIBFL_API.GetLoginTypeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLoginTypeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetLoginTypeResult;
        
        public GetLoginTypeResponseBody() {
        }
        
        public GetLoginTypeResponseBody(string GetLoginTypeResult) {
            this.GetLoginTypeResult = GetLoginTypeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUser", Namespace="http://tempuri.org/", Order=0)]
        public InsertElectronicExemplarBJ.LIBFL_API.GetUserRequestBody Body;
        
        public GetUserRequest() {
        }
        
        public GetUserRequest(InsertElectronicExemplarBJ.LIBFL_API.GetUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        public GetUserRequestBody() {
        }
        
        public GetUserRequestBody(string login) {
            this.login = login;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public InsertElectronicExemplarBJ.LIBFL_API.GetUserResponseBody Body;
        
        public GetUserResponse() {
        }
        
        public GetUserResponse(InsertElectronicExemplarBJ.LIBFL_API.GetUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public InsertElectronicExemplarBJ.LIBFL_API.ReaderInfo GetUserResult;
        
        public GetUserResponseBody() {
        }
        
        public GetUserResponseBody(InsertElectronicExemplarBJ.LIBFL_API.ReaderInfo GetUserResult) {
            this.GetUserResult = GetUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertIntoBasketRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertIntoBasket", Namespace="http://tempuri.org/", Order=0)]
        public InsertElectronicExemplarBJ.LIBFL_API.InsertIntoBasketRequestBody Body;
        
        public InsertIntoBasketRequest() {
        }
        
        public InsertIntoBasketRequest(InsertElectronicExemplarBJ.LIBFL_API.InsertIntoBasketRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertIntoBasketRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int PIN;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string IDSession;
        
        public InsertIntoBasketRequestBody() {
        }
        
        public InsertIntoBasketRequestBody(int PIN, string IDSession) {
            this.PIN = PIN;
            this.IDSession = IDSession;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertIntoBasketResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertIntoBasketResponse", Namespace="http://tempuri.org/", Order=0)]
        public InsertElectronicExemplarBJ.LIBFL_API.InsertIntoBasketResponseBody Body;
        
        public InsertIntoBasketResponse() {
        }
        
        public InsertIntoBasketResponse(InsertElectronicExemplarBJ.LIBFL_API.InsertIntoBasketResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertIntoBasketResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InsertIntoBasketResult;
        
        public InsertIntoBasketResponseBody() {
        }
        
        public InsertIntoBasketResponseBody(bool InsertIntoBasketResult) {
            this.InsertIntoBasketResult = InsertIntoBasketResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertArrayIntoBasketRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertArrayIntoBasket", Namespace="http://tempuri.org/", Order=0)]
        public InsertElectronicExemplarBJ.LIBFL_API.InsertArrayIntoBasketRequestBody Body;
        
        public InsertArrayIntoBasketRequest() {
        }
        
        public InsertArrayIntoBasketRequest(InsertElectronicExemplarBJ.LIBFL_API.InsertArrayIntoBasketRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertArrayIntoBasketRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public InsertElectronicExemplarBJ.LIBFL_API.ArrayOfInt PINs;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string IDSession;
        
        public InsertArrayIntoBasketRequestBody() {
        }
        
        public InsertArrayIntoBasketRequestBody(InsertElectronicExemplarBJ.LIBFL_API.ArrayOfInt PINs, string IDSession) {
            this.PINs = PINs;
            this.IDSession = IDSession;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertArrayIntoBasketResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertArrayIntoBasketResponse", Namespace="http://tempuri.org/", Order=0)]
        public InsertElectronicExemplarBJ.LIBFL_API.InsertArrayIntoBasketResponseBody Body;
        
        public InsertArrayIntoBasketResponse() {
        }
        
        public InsertArrayIntoBasketResponse(InsertElectronicExemplarBJ.LIBFL_API.InsertArrayIntoBasketResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertArrayIntoBasketResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InsertArrayIntoBasketResult;
        
        public InsertArrayIntoBasketResponseBody() {
        }
        
        public InsertArrayIntoBasketResponseBody(bool InsertArrayIntoBasketResult) {
            this.InsertArrayIntoBasketResult = InsertArrayIntoBasketResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExemplarStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExemplarStatus", Namespace="http://tempuri.org/", Order=0)]
        public InsertElectronicExemplarBJ.LIBFL_API.GetExemplarStatusRequestBody Body;
        
        public GetExemplarStatusRequest() {
        }
        
        public GetExemplarStatusRequest(InsertElectronicExemplarBJ.LIBFL_API.GetExemplarStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetExemplarStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string IDDATA;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BaseName;
        
        public GetExemplarStatusRequestBody() {
        }
        
        public GetExemplarStatusRequestBody(string IDDATA, string BaseName) {
            this.IDDATA = IDDATA;
            this.BaseName = BaseName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExemplarStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExemplarStatusResponse", Namespace="http://tempuri.org/", Order=0)]
        public InsertElectronicExemplarBJ.LIBFL_API.GetExemplarStatusResponseBody Body;
        
        public GetExemplarStatusResponse() {
        }
        
        public GetExemplarStatusResponse(InsertElectronicExemplarBJ.LIBFL_API.GetExemplarStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetExemplarStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetExemplarStatusResult;
        
        public GetExemplarStatusResponseBody() {
        }
        
        public GetExemplarStatusResponseBody(string GetExemplarStatusResult) {
            this.GetExemplarStatusResult = GetExemplarStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBookStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBookStatus", Namespace="http://tempuri.org/", Order=0)]
        public InsertElectronicExemplarBJ.LIBFL_API.GetBookStatusRequestBody Body;
        
        public GetBookStatusRequest() {
        }
        
        public GetBookStatusRequest(InsertElectronicExemplarBJ.LIBFL_API.GetBookStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBookStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public GetBookStatusRequestBody() {
        }
        
        public GetBookStatusRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBookStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBookStatusResponse", Namespace="http://tempuri.org/", Order=0)]
        public InsertElectronicExemplarBJ.LIBFL_API.GetBookStatusResponseBody Body;
        
        public GetBookStatusResponse() {
        }
        
        public GetBookStatusResponse(InsertElectronicExemplarBJ.LIBFL_API.GetBookStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBookStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetBookStatusResult;
        
        public GetBookStatusResponseBody() {
        }
        
        public GetBookStatusResponseBody(string GetBookStatusResult) {
            this.GetBookStatusResult = GetBookStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBookInfoByIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBookInfoByID", Namespace="http://tempuri.org/", Order=0)]
        public InsertElectronicExemplarBJ.LIBFL_API.GetBookInfoByIDRequestBody Body;
        
        public GetBookInfoByIDRequest() {
        }
        
        public GetBookInfoByIDRequest(InsertElectronicExemplarBJ.LIBFL_API.GetBookInfoByIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBookInfoByIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public GetBookInfoByIDRequestBody() {
        }
        
        public GetBookInfoByIDRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBookInfoByIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBookInfoByIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public InsertElectronicExemplarBJ.LIBFL_API.GetBookInfoByIDResponseBody Body;
        
        public GetBookInfoByIDResponse() {
        }
        
        public GetBookInfoByIDResponse(InsertElectronicExemplarBJ.LIBFL_API.GetBookInfoByIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBookInfoByIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetBookInfoByIDResult;
        
        public GetBookInfoByIDResponseBody() {
        }
        
        public GetBookInfoByIDResponseBody(string GetBookInfoByIDResult) {
            this.GetBookInfoByIDResult = GetBookInfoByIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBookInfoByInvNumberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBookInfoByInvNumber", Namespace="http://tempuri.org/", Order=0)]
        public InsertElectronicExemplarBJ.LIBFL_API.GetBookInfoByInvNumberRequestBody Body;
        
        public GetBookInfoByInvNumberRequest() {
        }
        
        public GetBookInfoByInvNumberRequest(InsertElectronicExemplarBJ.LIBFL_API.GetBookInfoByInvNumberRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBookInfoByInvNumberRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string invNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string baseName;
        
        public GetBookInfoByInvNumberRequestBody() {
        }
        
        public GetBookInfoByInvNumberRequestBody(string invNumber, string baseName) {
            this.invNumber = invNumber;
            this.baseName = baseName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBookInfoByInvNumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBookInfoByInvNumberResponse", Namespace="http://tempuri.org/", Order=0)]
        public InsertElectronicExemplarBJ.LIBFL_API.GetBookInfoByInvNumberResponseBody Body;
        
        public GetBookInfoByInvNumberResponse() {
        }
        
        public GetBookInfoByInvNumberResponse(InsertElectronicExemplarBJ.LIBFL_API.GetBookInfoByInvNumberResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBookInfoByInvNumberResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetBookInfoByInvNumberResult;
        
        public GetBookInfoByInvNumberResponseBody() {
        }
        
        public GetBookInfoByInvNumberResponseBody(string GetBookInfoByInvNumberResult) {
            this.GetBookInfoByInvNumberResult = GetBookInfoByInvNumberResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangePWDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangePWD", Namespace="http://tempuri.org/", Order=0)]
        public InsertElectronicExemplarBJ.LIBFL_API.ChangePWDRequestBody Body;
        
        public ChangePWDRequest() {
        }
        
        public ChangePWDRequest(InsertElectronicExemplarBJ.LIBFL_API.ChangePWDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChangePWDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int number;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        public ChangePWDRequestBody() {
        }
        
        public ChangePWDRequestBody(int number, string pwd) {
            this.number = number;
            this.pwd = pwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangePWDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangePWDResponse", Namespace="http://tempuri.org/", Order=0)]
        public InsertElectronicExemplarBJ.LIBFL_API.ChangePWDResponseBody Body;
        
        public ChangePWDResponse() {
        }
        
        public ChangePWDResponse(InsertElectronicExemplarBJ.LIBFL_API.ChangePWDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ChangePWDResponseBody {
        
        public ChangePWDResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ServiceSoapChannel : InsertElectronicExemplarBJ.LIBFL_API.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<InsertElectronicExemplarBJ.LIBFL_API.ServiceSoap>, InsertElectronicExemplarBJ.LIBFL_API.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InsertElectronicExemplarBJ.LIBFL_API.GetReaderInfoResponse InsertElectronicExemplarBJ.LIBFL_API.ServiceSoap.GetReaderInfo(InsertElectronicExemplarBJ.LIBFL_API.GetReaderInfoRequest request) {
            return base.Channel.GetReaderInfo(request);
        }
        
        public InsertElectronicExemplarBJ.LIBFL_API.ReaderInfo GetReaderInfo(string NumberReader) {
            InsertElectronicExemplarBJ.LIBFL_API.GetReaderInfoRequest inValue = new InsertElectronicExemplarBJ.LIBFL_API.GetReaderInfoRequest();
            inValue.Body = new InsertElectronicExemplarBJ.LIBFL_API.GetReaderInfoRequestBody();
            inValue.Body.NumberReader = NumberReader;
            InsertElectronicExemplarBJ.LIBFL_API.GetReaderInfoResponse retVal = ((InsertElectronicExemplarBJ.LIBFL_API.ServiceSoap)(this)).GetReaderInfo(inValue);
            return retVal.Body.GetReaderInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InsertElectronicExemplarBJ.LIBFL_API.AuthorizeResponse InsertElectronicExemplarBJ.LIBFL_API.ServiceSoap.Authorize(InsertElectronicExemplarBJ.LIBFL_API.AuthorizeRequest request) {
            return base.Channel.Authorize(request);
        }
        
        public string Authorize(string login, string password) {
            InsertElectronicExemplarBJ.LIBFL_API.AuthorizeRequest inValue = new InsertElectronicExemplarBJ.LIBFL_API.AuthorizeRequest();
            inValue.Body = new InsertElectronicExemplarBJ.LIBFL_API.AuthorizeRequestBody();
            inValue.Body.login = login;
            inValue.Body.password = password;
            InsertElectronicExemplarBJ.LIBFL_API.AuthorizeResponse retVal = ((InsertElectronicExemplarBJ.LIBFL_API.ServiceSoap)(this)).Authorize(inValue);
            return retVal.Body.AuthorizeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InsertElectronicExemplarBJ.LIBFL_API.HashPassResponse InsertElectronicExemplarBJ.LIBFL_API.ServiceSoap.HashPass(InsertElectronicExemplarBJ.LIBFL_API.HashPassRequest request) {
            return base.Channel.HashPass(request);
        }
        
        public string HashPass(string strPassword, string strSol) {
            InsertElectronicExemplarBJ.LIBFL_API.HashPassRequest inValue = new InsertElectronicExemplarBJ.LIBFL_API.HashPassRequest();
            inValue.Body = new InsertElectronicExemplarBJ.LIBFL_API.HashPassRequestBody();
            inValue.Body.strPassword = strPassword;
            inValue.Body.strSol = strSol;
            InsertElectronicExemplarBJ.LIBFL_API.HashPassResponse retVal = ((InsertElectronicExemplarBJ.LIBFL_API.ServiceSoap)(this)).HashPass(inValue);
            return retVal.Body.HashPassResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InsertElectronicExemplarBJ.LIBFL_API.GetLoginTypeResponse InsertElectronicExemplarBJ.LIBFL_API.ServiceSoap.GetLoginType(InsertElectronicExemplarBJ.LIBFL_API.GetLoginTypeRequest request) {
            return base.Channel.GetLoginType(request);
        }
        
        public string GetLoginType(string login) {
            InsertElectronicExemplarBJ.LIBFL_API.GetLoginTypeRequest inValue = new InsertElectronicExemplarBJ.LIBFL_API.GetLoginTypeRequest();
            inValue.Body = new InsertElectronicExemplarBJ.LIBFL_API.GetLoginTypeRequestBody();
            inValue.Body.login = login;
            InsertElectronicExemplarBJ.LIBFL_API.GetLoginTypeResponse retVal = ((InsertElectronicExemplarBJ.LIBFL_API.ServiceSoap)(this)).GetLoginType(inValue);
            return retVal.Body.GetLoginTypeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InsertElectronicExemplarBJ.LIBFL_API.GetUserResponse InsertElectronicExemplarBJ.LIBFL_API.ServiceSoap.GetUser(InsertElectronicExemplarBJ.LIBFL_API.GetUserRequest request) {
            return base.Channel.GetUser(request);
        }
        
        public InsertElectronicExemplarBJ.LIBFL_API.ReaderInfo GetUser(string login) {
            InsertElectronicExemplarBJ.LIBFL_API.GetUserRequest inValue = new InsertElectronicExemplarBJ.LIBFL_API.GetUserRequest();
            inValue.Body = new InsertElectronicExemplarBJ.LIBFL_API.GetUserRequestBody();
            inValue.Body.login = login;
            InsertElectronicExemplarBJ.LIBFL_API.GetUserResponse retVal = ((InsertElectronicExemplarBJ.LIBFL_API.ServiceSoap)(this)).GetUser(inValue);
            return retVal.Body.GetUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InsertElectronicExemplarBJ.LIBFL_API.InsertIntoBasketResponse InsertElectronicExemplarBJ.LIBFL_API.ServiceSoap.InsertIntoBasket(InsertElectronicExemplarBJ.LIBFL_API.InsertIntoBasketRequest request) {
            return base.Channel.InsertIntoBasket(request);
        }
        
        public bool InsertIntoBasket(int PIN, string IDSession) {
            InsertElectronicExemplarBJ.LIBFL_API.InsertIntoBasketRequest inValue = new InsertElectronicExemplarBJ.LIBFL_API.InsertIntoBasketRequest();
            inValue.Body = new InsertElectronicExemplarBJ.LIBFL_API.InsertIntoBasketRequestBody();
            inValue.Body.PIN = PIN;
            inValue.Body.IDSession = IDSession;
            InsertElectronicExemplarBJ.LIBFL_API.InsertIntoBasketResponse retVal = ((InsertElectronicExemplarBJ.LIBFL_API.ServiceSoap)(this)).InsertIntoBasket(inValue);
            return retVal.Body.InsertIntoBasketResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InsertElectronicExemplarBJ.LIBFL_API.InsertArrayIntoBasketResponse InsertElectronicExemplarBJ.LIBFL_API.ServiceSoap.InsertArrayIntoBasket(InsertElectronicExemplarBJ.LIBFL_API.InsertArrayIntoBasketRequest request) {
            return base.Channel.InsertArrayIntoBasket(request);
        }
        
        public bool InsertArrayIntoBasket(InsertElectronicExemplarBJ.LIBFL_API.ArrayOfInt PINs, string IDSession) {
            InsertElectronicExemplarBJ.LIBFL_API.InsertArrayIntoBasketRequest inValue = new InsertElectronicExemplarBJ.LIBFL_API.InsertArrayIntoBasketRequest();
            inValue.Body = new InsertElectronicExemplarBJ.LIBFL_API.InsertArrayIntoBasketRequestBody();
            inValue.Body.PINs = PINs;
            inValue.Body.IDSession = IDSession;
            InsertElectronicExemplarBJ.LIBFL_API.InsertArrayIntoBasketResponse retVal = ((InsertElectronicExemplarBJ.LIBFL_API.ServiceSoap)(this)).InsertArrayIntoBasket(inValue);
            return retVal.Body.InsertArrayIntoBasketResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InsertElectronicExemplarBJ.LIBFL_API.GetExemplarStatusResponse InsertElectronicExemplarBJ.LIBFL_API.ServiceSoap.GetExemplarStatus(InsertElectronicExemplarBJ.LIBFL_API.GetExemplarStatusRequest request) {
            return base.Channel.GetExemplarStatus(request);
        }
        
        public string GetExemplarStatus(string IDDATA, string BaseName) {
            InsertElectronicExemplarBJ.LIBFL_API.GetExemplarStatusRequest inValue = new InsertElectronicExemplarBJ.LIBFL_API.GetExemplarStatusRequest();
            inValue.Body = new InsertElectronicExemplarBJ.LIBFL_API.GetExemplarStatusRequestBody();
            inValue.Body.IDDATA = IDDATA;
            inValue.Body.BaseName = BaseName;
            InsertElectronicExemplarBJ.LIBFL_API.GetExemplarStatusResponse retVal = ((InsertElectronicExemplarBJ.LIBFL_API.ServiceSoap)(this)).GetExemplarStatus(inValue);
            return retVal.Body.GetExemplarStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InsertElectronicExemplarBJ.LIBFL_API.GetBookStatusResponse InsertElectronicExemplarBJ.LIBFL_API.ServiceSoap.GetBookStatus(InsertElectronicExemplarBJ.LIBFL_API.GetBookStatusRequest request) {
            return base.Channel.GetBookStatus(request);
        }
        
        public string GetBookStatus(string id) {
            InsertElectronicExemplarBJ.LIBFL_API.GetBookStatusRequest inValue = new InsertElectronicExemplarBJ.LIBFL_API.GetBookStatusRequest();
            inValue.Body = new InsertElectronicExemplarBJ.LIBFL_API.GetBookStatusRequestBody();
            inValue.Body.id = id;
            InsertElectronicExemplarBJ.LIBFL_API.GetBookStatusResponse retVal = ((InsertElectronicExemplarBJ.LIBFL_API.ServiceSoap)(this)).GetBookStatus(inValue);
            return retVal.Body.GetBookStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InsertElectronicExemplarBJ.LIBFL_API.GetBookInfoByIDResponse InsertElectronicExemplarBJ.LIBFL_API.ServiceSoap.GetBookInfoByID(InsertElectronicExemplarBJ.LIBFL_API.GetBookInfoByIDRequest request) {
            return base.Channel.GetBookInfoByID(request);
        }
        
        public string GetBookInfoByID(string id) {
            InsertElectronicExemplarBJ.LIBFL_API.GetBookInfoByIDRequest inValue = new InsertElectronicExemplarBJ.LIBFL_API.GetBookInfoByIDRequest();
            inValue.Body = new InsertElectronicExemplarBJ.LIBFL_API.GetBookInfoByIDRequestBody();
            inValue.Body.id = id;
            InsertElectronicExemplarBJ.LIBFL_API.GetBookInfoByIDResponse retVal = ((InsertElectronicExemplarBJ.LIBFL_API.ServiceSoap)(this)).GetBookInfoByID(inValue);
            return retVal.Body.GetBookInfoByIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InsertElectronicExemplarBJ.LIBFL_API.GetBookInfoByInvNumberResponse InsertElectronicExemplarBJ.LIBFL_API.ServiceSoap.GetBookInfoByInvNumber(InsertElectronicExemplarBJ.LIBFL_API.GetBookInfoByInvNumberRequest request) {
            return base.Channel.GetBookInfoByInvNumber(request);
        }
        
        public string GetBookInfoByInvNumber(string invNumber, string baseName) {
            InsertElectronicExemplarBJ.LIBFL_API.GetBookInfoByInvNumberRequest inValue = new InsertElectronicExemplarBJ.LIBFL_API.GetBookInfoByInvNumberRequest();
            inValue.Body = new InsertElectronicExemplarBJ.LIBFL_API.GetBookInfoByInvNumberRequestBody();
            inValue.Body.invNumber = invNumber;
            inValue.Body.baseName = baseName;
            InsertElectronicExemplarBJ.LIBFL_API.GetBookInfoByInvNumberResponse retVal = ((InsertElectronicExemplarBJ.LIBFL_API.ServiceSoap)(this)).GetBookInfoByInvNumber(inValue);
            return retVal.Body.GetBookInfoByInvNumberResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InsertElectronicExemplarBJ.LIBFL_API.ChangePWDResponse InsertElectronicExemplarBJ.LIBFL_API.ServiceSoap.ChangePWD(InsertElectronicExemplarBJ.LIBFL_API.ChangePWDRequest request) {
            return base.Channel.ChangePWD(request);
        }
        
        public void ChangePWD(int number, string pwd) {
            InsertElectronicExemplarBJ.LIBFL_API.ChangePWDRequest inValue = new InsertElectronicExemplarBJ.LIBFL_API.ChangePWDRequest();
            inValue.Body = new InsertElectronicExemplarBJ.LIBFL_API.ChangePWDRequestBody();
            inValue.Body.number = number;
            inValue.Body.pwd = pwd;
            InsertElectronicExemplarBJ.LIBFL_API.ChangePWDResponse retVal = ((InsertElectronicExemplarBJ.LIBFL_API.ServiceSoap)(this)).ChangePWD(inValue);
        }
    }
}
